package main

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"strings"
	"time"

	pb "grpc-lesson/gen/search"

	"google.golang.org/grpc"
)

// crawlServer implements the CrawlService interface generated by protoc.
// If we don't implement every method the compiler refuses to compile.
// This is the contract enforcement gRPC gives you — you cannot forget a method.
type crawlServer struct {
	// UnimplementedCrawlServiceServer must be embedded.
	// It provides default implementations of any methods we don't implement,
	// returning "not implemented" errors. This is a gRPC Go convention that
	// makes your server forward-compatible when new methods are added to the proto
	pb.UnimplementedCrawlServiceServer
}

// Crawl handles a single URL crawl request.
// In production this calls Spider-rs internals to fetch and extract the page.
// Here we simulate it with a mock response.
func (s *crawlServer) Crawl(ctx context.Context, req *pb.CrawlRequest) (*pb.CrawlResponse, error) {
	slog.Info("crawl request received", "url", req.Url, "javascript", req.Javascript)	
	
	//Simulated
	time.Sleep(50 * time.Millisecond)

	// Mock extracted markdown — in production this is Spider-rs output
	markdown := fmt.Sprintf(
		"# Content from %s\n\n"+
		"This is the extracted markdown content from the page. "+
		"In production Spider-rs fetches the real page and returns clean LLM-ready markdown.\n\n"+
		"JavaScript rendering was requested: %v\n"+
		"Crawled at: %s",
		req.Url,
		req.Javascript,
		time.Now().Format(time.RFC3339),
	)
	return  &pb.CrawlResponse{
		Url: req.Url,
		Markdown: markdown,
		TokenCount: int32(len(strings.Fields(markdown))),  // word count as token approximation
		StatusCode: 200,
		Error: "",
	}, nil
}

// BatchCrawl handles multiple URLs in one call.
// In production Spider-rs fetches all URLs concurrently.
func (s *crawlServer) BatchCrawl(ctx context.Context, req *pb.BatchCrawlRequest) (*pb.BatchCrawlResponse, error) {
	slog.Info("batch crawl request", "url_count", len(req.Requests))

	results := make([]*pb.CrawlResponse, 0, len(req.Requests))

	for _,  crawlReq := range req.Requests {
		// In production these fire concurrently via goroutines.
		// For clarity here we call sequentially.
		resp, err := s.Crawl(ctx, crawlReq)
		if err != nil {
			resp =&pb.CrawlResponse{
				Url: crawlReq.Url,
				Error: err.Error(),
			}
		}
		results = append(results, resp)
	}
	return &pb.BatchCrawlResponse{Results: results}, nil
}

// StreamCrawl is server-side streaming — results stream back as each URL completes.
// The client does not wait for all URLs. It processes each result the moment it arrives.
// This is how the OpenSearch engine returns partial results to agents immediately.
func (s *crawlServer) StreamCrawl(req *pb.BatchCrawlRequest, stream pb.CrawlService_StreamCrawlServer) error {
	slog.Info("stream crawl request", "url_count", len(req.Requests))

	for _, crawlReq := range req.Requests {
		// Check if the client cancelled — important for long-running streams
		if err := stream.Context().Err(); err != nil{
			slog.Info("stream cancelled by client")
			return err
		}
		resp, err := s.Crawl(stream.Context(), crawlReq)
		if err!= nil {
			continue
		}

		// Send each result as it completes — client receives immediately
		if err := stream.Send(resp); err != nil {
			slog.Error("failed to send stream result", "error", err)
			return err
		}
		slog.Info("streamed result", "url", crawlReq.Url)
	}
	return  nil
}

func main() {
	listener, err :=net.Listen("tcp", ":50051")
	if err != nil{
		slog.Error("failed to listen", "error", err)
		return
	}

	// grpc.NewServer() is the equivalent of http.NewServeMux() —
	// it creates the server but does not start it yet.
	grpcServer := grpc.NewServer()

	// Register our implementation with the server.
	// The generated RegisterCrawlServiceServer function wires it together.
	pb.RegisterCrawlServiceServer(grpcServer, &crawlServer{})

	slog.Info("gRPC server running on :50051")

	// Serve blocks until the server is stopped — same as http.ListenAndServe.
	if err :=grpcServer.Serve(listener); err != nil {
		slog.Error("server failed", "error", err)

	}

}